---
# tasks file for ansible-role-node

- include_vars: "defaults/main.yml"

- name: Ensure apt-transport-https is installed.
  apt: name=apt-transport-https state=present
  tags: install

- name: Add Nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present
  tags: install

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ ansible_role_node.nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ ansible_role_node.nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo
  tags: install

- name: Update apt cache if repo was added.
  apt: update_cache=yes
  when: node_repo.changed
  tags: install

- name: Ensure Node.js and npm are installed.
  apt: "name=nodejs={{ ansible_role_node.nodejs_version|regex_replace('x', '') }}* state=present"
  tags: install

- name: Define local_nodejs_install_npm_user as ansible_role_node.nodejs_install_npm_user
  set_fact:
    local_nodejs_install_npm_user: "{{ ansible_role_node.nodejs_install_npm_user }}"
  when: ansible_role_node.nodejs_install_npm_user is defined
  tags: install

- debug: var=local_nodejs_install_npm_user
  tags: install

- name: Create npm global directory
  file:
    path: "{{ ansible_role_node.npm_config_prefix }}"
    owner: "{{ local_nodejs_install_npm_user }}"
    group: "{{ local_nodejs_install_npm_user }}"
    state: directory
  tags: install

- name: Add npm_config_prefix bin directory to global $PATH.
  template:
    src: npm.sh.j2
    dest: /etc/profile.d/npm.sh
    mode: 0644
  tags: install

- name: Ensure npm global packages are installed.
  npm:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default('latest') }}"
    global: yes
    state: latest
  environment:
    NPM_CONFIG_PREFIX: "{{ ansible_role_node.npm_config_prefix }}"
    NODE_PATH: "{{ ansible_role_node.npm_config_prefix }}/lib/node_modules"
    NPM_CONFIG_UNSAFE_PERM: "{{ ansible_role_node.npm_config_unsafe_perm }}"
  with_items: "{{ ansible_role_node.nodejs_npm_global_packages }}"
  tags: install

- name: Install packages defined in a given package.json.
  npm:
    path: "{{ ansible_role_node.nodejs_package_json_path }}"
  when: ansible_role_node.nodejs_package_json_path is defined and ansible_role_node.nodejs_package_json_path
  tags: install
